### ISSUE TITLE
Progress Bar Not Showing On Some Transcripts on Riverside Fixit+

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/transcript-editor#102]
Because:
some transcripts with progress do not show progress bar
http://wrvrtranscripts.americanarchive.org/?sort_by=completeness&order=desc&q=&page=1

Done When:
they do

**Comment by foglabs-zen** [comment]
http://wrvrtranscripts.americanarchive.org/transcripts/cpb-aacip_528-pz51g0k72b

**Comment by singlesoliloquy** [comment]
@foglabs @jasoncorum this is done right?

**Comment by singlesoliloquy** [comment]
http://wrvrtranscripts.americanarchive.org/transcripts/cpb-aacip-528-jq0sq8rp92 here is one that's not showing a bar

**Comment by singlesoliloquy** [comment]
Closed, the bars is there now.
