### ISSUE TITLE
LPB Transcripts for FixIT

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/transcript-editor#116]
## Done When

Transcripts from GUID list are added to Louisiana Public Broadcasting.

[https://app.zenhub.com/files/116399818/3b8b2f2b-95c2-41cc-bb76-91ff7b9f5689/download](https://app.zenhub.com/files/116399818/3b8b2f2b-95c2-41cc-bb76-91ff7b9f5689/download)

**Comment by jasoncorum** [comment]
Ingested the list. Looks like we don't have a transcript_url for this one, though: cpb-aacip/17-12m64qgs
https://americanarchive.org/catalog/cpb-aacip-17-12m64qgs
