### ISSUE TITLE
Add Peabody Transcripts to Fixit+

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/transcript-editor#118]
## User Story
We've received Peabody transcripts from UGA and need to add them to Fixit+.

## Additional Information
Zip file: [https://app.zenhub.com/files/116399818/10e81ce4-1de8-4ae9-8ab6-760297f765b0/download](https://app.zenhub.com/files/116399818/10e81ce4-1de8-4ae9-8ab6-760297f765b0/download)

## Done Looks Like
The transcripts are added and ready for correction in a new collection called Peabody.

**Comment by singlesoliloquy** [comment]
Hey @jasoncorum, do we know that vtt files work? That's the thing I missed with this is we need to see that vtt displays alright.

**Comment by jasoncorum** [comment]
VTT should display fine as the application actually converts JSON to VTT as part of our import process.

Additional note:

These are going in to FixIt+ with a collection name of: Peabody Collection - UGA.

**Comment by jasoncorum** [comment]
Iceboxing because this got pushed back and we don't have the records ready for ingest.
