### ISSUE TITLE
Add transcript for Free and Brave - James Baldwill

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/transcript-editor#123]
## User Story
As a user, I don't want this transcript to suck so bad.

## Additional Information
User complained about it to Ryn. [https://americanarchive.org/catalog/cpb-aacip-28-9z90863j5g](https://americanarchive.org/catalog/cpb-aacip-28-9z90863j5g). 

## Done Looks Like
The transcript is added to Fixit+

**Comment by jasoncorum** [comment]
Done: http://fixitplus.americanarchive.org/transcripts/cpb-aacip-28-9z90863j5g
