### ISSUE TITLE
Adding two Media for the Public Good transcripts to FixIT

### ISSUE THREAD

**Issue by mivillesvik** [WGBH-MLA/transcript-editor#127]
## User Story

Casey has approved getting all of the Media for the Public Good items into the FixiT+! This is a new organization that would be added to the FixIT+

I'll update the transcript status and organization (I put the org as "Media for the Public Good" since I wasn't sure if the backslash or comma in the full name "Media for the Public Good, Inc. / OutCasting Media" would cause issues)

GUIDs are: 

cpb-aacip-04aa1e87254
cpb-aacip-06c46a8d772
cpb-aacip-082d9ec96a2
cpb-aacip-0a727c0f3ef
cpb-aacip-0b7cab0219b
cpb-aacip-0eaf33440e3
cpb-aacip-122a5fd2dcc
cpb-aacip-123b100db2a
cpb-aacip-139922e015b
cpb-aacip-184b775b1f6
cpb-aacip-1ed3c325625
cpb-aacip-1f58ca55540
cpb-aacip-1f7b7615667
cpb-aacip-2177749f249
cpb-aacip-22ddc30dd65
cpb-aacip-24cfeac6bbd
cpb-aacip-26781e684ff
cpb-aacip-26bc78df201
cpb-aacip-2cd6e4aed30
cpb-aacip-2d5752cac0f
cpb-aacip-2f05ac415b9
cpb-aacip-30126147adf
cpb-aacip-30f8062ad79
cpb-aacip-31756823c65
cpb-aacip-3251b83751d
cpb-aacip-33590e0f003
cpb-aacip-34d58b175d1
cpb-aacip-352668291b6
cpb-aacip-3595f1b2363
cpb-aacip-3658223d3ca
cpb-aacip-376d703a2f2
cpb-aacip-3d2b102cc89
cpb-aacip-3e07ab2036e
cpb-aacip-401ad4c5eda
cpb-aacip-42a70fbbbf1
cpb-aacip-4323c456e18
cpb-aacip-4343469b7a8
cpb-aacip-47157e67fe2
cpb-aacip-47b90ef7a91
cpb-aacip-488202bebd4
cpb-aacip-4bc5d750a33
cpb-aacip-4e287201e48
cpb-aacip-4f40e330284
cpb-aacip-531c26468d5
cpb-aacip-57b96437b63
cpb-aacip-5d51494ad13
cpb-aacip-5eb44e1e37d
cpb-aacip-5fd66b4d2ee
cpb-aacip-613c892680b
cpb-aacip-6445c3e087a
cpb-aacip-64cc2fa6a1e
cpb-aacip-6592719b4c0
cpb-aacip-68078ebebed
cpb-aacip-68d7e318420
cpb-aacip-692255c30ec
cpb-aacip-6e625dd2269
cpb-aacip-7085df313bd
cpb-aacip-727d2f96ac7
cpb-aacip-73990fbd6e1
cpb-aacip-757b826e53f
cpb-aacip-7590a9818e8
cpb-aacip-776c44b415d
cpb-aacip-7d2c9fd58ce
cpb-aacip-7d4964115d9
cpb-aacip-7e1cc870862
cpb-aacip-7e683dd5ef4
cpb-aacip-7f9ed8037fb
cpb-aacip-80327cd8473
cpb-aacip-860bf631c0d
cpb-aacip-88fd8d46a5a
cpb-aacip-8c169fab2d6
cpb-aacip-8f42be4e2d6
cpb-aacip-8f5f4c9eef0
cpb-aacip-904c7d88cf7
cpb-aacip-912ef1a98d0
cpb-aacip-9464575440f
cpb-aacip-9bfb0eb8632
cpb-aacip-9c36e80359a
cpb-aacip-9d89fc0c8d5
cpb-aacip-9d9ef225d0e
cpb-aacip-9e22a050696
cpb-aacip-a128180de5d
cpb-aacip-a13535878df
cpb-aacip-a414b629fbe
cpb-aacip-a53e2c5181a
cpb-aacip-a5df7454f65
cpb-aacip-ad5b63a01fb
cpb-aacip-b0221700af2
cpb-aacip-b0f53fa1764
cpb-aacip-b2e2f837f64
cpb-aacip-b39d4df4227
cpb-aacip-b57796c29d5
cpb-aacip-b66d8a3b5e3
cpb-aacip-b7f61d240fb
cpb-aacip-b952c98feab
cpb-aacip-bb4df2b263f
cpb-aacip-c055fa84dd2
cpb-aacip-c24606332f6
cpb-aacip-c2854fe9384
cpb-aacip-c3c7f975fde
cpb-aacip-cab9fc29622
cpb-aacip-cb63265b467
cpb-aacip-cb6f8d1d85d
cpb-aacip-ccbf7d7472d
cpb-aacip-d13d61cef89
cpb-aacip-d3bb38e2f0a
cpb-aacip-d57c1ee9f98
cpb-aacip-d6ba42e29a0
cpb-aacip-d71a6e919ee
cpb-aacip-d84b53621ed
cpb-aacip-db7831c9ad0
cpb-aacip-e287324abb1
cpb-aacip-e42bda63bcc
cpb-aacip-e4bed08051f
cpb-aacip-ec48dc4afd6
cpb-aacip-ec94273ff1e
cpb-aacip-ed3af0d2692
cpb-aacip-edf3f5a9694
cpb-aacip-ee127c55f48
cpb-aacip-ee6f36fae1f
cpb-aacip-eea3efd4b41
cpb-aacip-ef7ff95004b
cpb-aacip-f07d148abfa
cpb-aacip-f23afe945df
cpb-aacip-f5c5fc61ff3
cpb-aacip-fc93ccd0946
cpb-aacip-fcc66e07918
cpb-aacip-fd270959ff6
cpb-aacip-fe0b68856a0

**Comment by singlesoliloquy** [comment]
@mivillesvik do you need to check in on this?

**Comment by mivillesvik** [comment]
Thank you for the reminder! Yes, Casey said we can put the other OutCasting transcripts on the FixIT+, I can update the ticket to include the full list, and I'll work on updating the AMS2 annotations accordingly!
