### ISSUE TITLE
Adding a transcript back to WRVR's fixIT+ instance

### ISSUE THREAD

**Issue by mivillesvik** [WGBH-MLA/transcript-editor#131]
## User Story
Hi, Vince from WRVR noticed that one of the transcripts that was taken down from the WRVR fixIT+ instance has some editing issues and was wondering if it can be re-added? I checked and it's in the ORR and has the appropriate tags.

GUID is:
cpb-aacip-528-xg9f47j76d
Thanks!

**Comment by foglabs-zen** [comment]
added https://wrvrtranscripts.americanarchive.org/transcripts/cpb-aacip-528-xg9f47j76d
