### ISSUE TITLE
WRVR - fixit user cannot log in

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/transcript-editor#137]
**Describe the bug**
User cannot log in to WRVR Fixit+

**To Reproduce**
User tries to login and gets an error message. Same with other volunteers at WRVR.

![image.png](https://images.zenhubusercontent.com/5e5e7f2e572e74e6537e269f/5963d983-9b98-4eda-bd7f-d28aeec324a7)

**Done When**
User can log in

**Comment by foglabs-zen** [comment]
will be fixed via fixit upgrades
