### ISSUE TITLE
FixIt+ all_uids endpoint

### ISSUE THREAD

**Issue by jasoncorum** [WGBH-MLA/transcript-editor#138]
The all_uids endpoint on FixIt+ doesn't seem to working. It looks like it's returning a page not found:

https://fixitplus.americanarchive.org/all_uids

The same endpoing IS working on the WRVR instance: 

http://wrvrtranscripts.americanarchive.org/all_uids

**Done When** the all_uids endpoint returns a list of all UIDs.

**Comment by ekemeyer** [comment]
can't replicate
