### ISSUE TITLE
Adding a transcript to the FixIT+ (during next deploy to FixIT+)

### ISSUE THREAD

**Issue by mivillesvik** [WGBH-MLA/transcript-editor#149]
## User Story
Hello, we got a request in through the AAPB Notification hotline about a transcript for Debate: Baldwin vs. Buckley (https://americanarchive.org/catalog/cpb-aacip-151-sn00z71m54) not having a corrected transcript -- since this is an important debate, do you mind adding it to the FixIT+ next time more items are added to the site?
Thanks!

## Additional Information
The program is produced by BBC, but contributed to Library of Congress/Film and Media Archive at WUSTL

## Done Looks Like
The transcript will be in the FixIT+

**Comment by ekemeyer** [comment]
transcript was added, and since then fixed - pushed updated transcript to AAPB
