### ISSUE TITLE
Taking down and re-adding a transcript to FixIT+

### ISSUE THREAD

**Issue by mivillesvik** [WGBH-MLA/transcript-editor#150]
## User Story
Alan has found a transcript that is mostly non-usable, is it possible to re-run the transcript in the Kaldi and then replace the AAPB transcript with the new one? Record is: https://americanarchive.org/catalog/cpb-aacip-293-09w0vvkm

## Done Looks Like
Hopefully the transcript will have a new, more usable transcript!

**Comment by ekemeyer** [comment]
@foo4thought this is an old ticket, but still relevant. Can you add this to the whisper queue and replace the transcript we currently have? Once that is done I can toss it in fixit+

**Comment by foo4thought** [comment]
objects uploaded to ASR system

**Comment by foo4thought** [comment]
objects uploaded to S3 for AAPB, reindexed on AAPB.
NOTE:  database AAPB_Enhancements shows that this run through ASR did result in a larger transcript file BUT the earier version has also completed its run through fixitplus!  

`s3://americanarchive.org/transcripts/cpb-aacip-293-09w0vvkm/cpb-aacip-293-09w0vvkm-transcript.json | 1729 | 2023-09-08T16:25:45.000Z`
versus
`s3://americanarchive.org/transcripts/cpb-aacip-293-09w0vvkm/cpb-aacip-293-09w0vvkm-transcript.json | 108973 | 2024-09-03T15:11:35.000Z`
