### ISSUE TITLE
Adding an item to the FixIT+

### ISSUE THREAD

**Issue by mivillesvik** [WGBH-MLA/transcript-editor#152]
## User Story
Hi, we've had a request to add a transcript to the FixIT+ (cpb-aacip-28-959c53fb23), does someone mind adding it there? 

The record in question already has its organization annotation, and I can update the transcript status annotation once it's added to FixIT+
Thanks!

## Done Looks Like
The transcript will be in FixIT+

**Comment by ekemeyer** [comment]
Added!
