### ISSUE TITLE
Adding files to FixIT+

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/transcript-editor#169]
# Details 
Hi, The folks at Bill Moyers would like to request that the below list of transcripts be added to the FixIT+:
cpb-aacip-064d83c132b
cpb-aacip-0f3879e2f22
cpb-aacip-1a365705273
cpb-aacip-2be58eb06c9
cpb-aacip-3dd964e5869
cpb-aacip-3dd964e5869
cpb-aacip-6347cac1287
cpb-aacip-8f8fac7626b
cpb-aacip-9fa9c58dd63
cpb-aacip-a32723d5821
cpb-aacip-ca9a4ae8d49
cpb-aacip-d6ab6d21583
cpb-aacip-dc85d0b63a4
Thanks!

Submitted by: Miranda Villesvik
Priority: Medium (within this month)
URL: 
Slack message thread: 

another request to go ahead and do while on this: #152, #149, #124

**Comment by foglabs** [comment]
@mivillesvik 
hey, I entered these to be ingested, but some of them need a metadata fix first.

These were already in FIXIT+, so all set!
cpb-aacip-064d83c132b
cpb-aacip-8f8fac7626b
cpb-aacip-a32723d5821
cpb-aacip-dc85d0b63a4

These are missing the <pbcoreAnnotation type="organization"> annotation on AAPB, which is required to pair the record with a 'Collection' on FIXIT+. This annotation should ideally be added in AMS2, then pushed to AAPB.
cpb-aacip-0f3879e2f22
cpb-aacip-1a365705273
cpb-aacip-2be58eb06c9
cpb-aacip-3dd964e5869
cpb-aacip-6347cac1287
cpb-aacip-9fa9c58dd63
cpb-aacip-ca9a4ae8d49
cpb-aacip-d6ab6d21583


Thanks!

**Comment by ekemeyer** [comment]
@foglabs - Miranda has updated these, they're ready to go!

**Comment by foglabs** [comment]
@mivillesvik @ekemeyer 
Ok! I was able to add:
cpb-aacip-2be58eb06c9

But unfortunately, these ones:
cpb-aacip-0f3879e2f22
cpb-aacip-1a365705273
cpb-aacip-3dd964e5869
cpb-aacip-6347cac1287
cpb-aacip-9fa9c58dd63
cpb-aacip-ca9a4ae8d49
cpb-aacip-d6ab6d21583

can't be added, because FIXIT+ doesn't support the ingest of .txt transcripts.

**Comment by ekemeyer** [comment]
We're all set! Thanks @foglabs! Miranda will be letting the Moyer's folks know about the recordings that could not go to Fixit+.
