### ISSUE TITLE
Replacing three Nebraska transcripts in FixIT+

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/transcript-editor#180]
# Details 
When Kevin ran the transcript output on Nebraska transcripts, there were some oddities, including three transcripts that just said "you" the whole time. Alexis' team were able to re-run the transcripts on their end and generated actual words! Do you mind putting the three replacement transcripts (sent to Erica via Slack) into the S3 and into the FixIT+ so that they replace the weirdo transcripts we currently have? 
For reference, the three GUIDs are: 
cpb-aacip-e6407f3804c
cpb-aacip-7b46a69b242
cpb-aacip-81995f80c5d

Submitted by: Miranda!
CC in communications: 
Priority: High (within the week)
URL: 
Slack message thread:

**Comment by ekemeyer** [comment]
Attaching the transcripts from Nebraska
[cpb-aacip-7b46a69b242.txt](https://github.com/user-attachments/files/17078973/cpb-aacip-7b46a69b242.txt)
[cpb-aacip-81995f80c5d.txt](https://github.com/user-attachments/files/17078974/cpb-aacip-81995f80c5d.txt)
[cpb-aacip-e6407f3804c.txt](https://github.com/user-attachments/files/17078975/cpb-aacip-e6407f3804c.txt)

**Comment by foo4thought** [comment]
1. convert text format from CR/LF to LF and modify parsing code of existing script for VTT conversion 
2. ignore lines like '^Speaker [0-9]:' 
3. reformat HH:MM:SS:FF to HH:MM:SS.FF
4. reformat time range separator to be ' --> '
5. check result
NOTE:  output is not frame accurate (the decimal-format conversion involved no math)
 
[cpb-aacip-7b46a69b242-transcript.json](https://github.com/user-attachments/files/17081173/cpb-aacip-7b46a69b242-transcript.json)
[cpb-aacip-81995f80c5d-transcript.json](https://github.com/user-attachments/files/17081174/cpb-aacip-81995f80c5d-transcript.json)
[cpb-aacip-e6407f3804c-transcript.json](https://github.com/user-attachments/files/17081175/cpb-aacip-e6407f3804c-transcript.json)

**Comment by foo4thought** [comment]
[foo_vtt.sh.txt](https://github.com/user-attachments/files/17081187/foo_vtt.sh.txt)

**Comment by foo4thought** [comment]
LOL it's a shell script but not permitted here with that name

**Comment by ekemeyer** [comment]
replaced .json files in s3 with improved transcripts. Updated them in Fixit+ as well.
