### ISSUE TITLE
Completed transcripts not showing 100% 

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/transcript-editor#70]
Example: http://fixitplus.americanarchive.org/transcripts/cpb-aacip_52-82x3fpzd

This transcript has all individual lines marked as completed (as far as I can tell) and no red flags on any lines. However, the interface is showing it only as 97% completed. Can we check in the database and see if there are lines that aren't actually being stored as completed?

**Comment by ekemeyer** [comment]
duplicated
