### ISSUE TITLE
Develop automated workflow for downloading corrected transcripts

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/transcript-editor#97]
Desired workflow:
- [ ] run a task to get a list of GUIDs that have the completed status (or something equivalent)
- [ ] run a script to hit the aapb transcript endpoint for a specific list of GUIDs (I'd like to be able to do this for the GUIDs I get from the first task, but also be able to add any other ones I want, so the two tasks don't have to feed directly into each other)
- [ ] use script Kevin wrote to upload new transcript to americanarchive.org S3 that moves the current transcript and then adds the new one, so it doesn't overwrite the previous transcript, in case we want it in the future.
- [ ] submit batch metadata updates to the transcript status for each GUID to set status to Correct.
- [ ] reindex affected GUIDs on AAPB.

**Comment by foglabs-zen** [comment]
This work is done, but needs to be released. It adds a new boolean field `:released` to the `Transcript` model, that marks whether a completed transcript has been synced to AAPB, and adds a ruby wrapper for Kevin's transcript versioning script. The user must ssh into fixitplus, and then run `workflow.rb`. This will generate the transcript files for all unreleased correct transcripts, and then push them into AAPB's transcript folder on S3.
